export enum RolesEnum {
  SYSTEM_ADMIN = 1, // TODO: Rename to SUP_ADMIN
  IT_SUPPORT = 2, // DEPRECATED
  CONTRIBUTOR = 3,
  GLOBAL = 4, // DEPRECATED
  CONTRACT_CONTRIBUTOR = 5, // DEPRECATED
  RESULT_CONTRIBUTOR = 6, // DEPRECATED
  TECHNICAL_SUPPORT = 7, // TODO: Rename to DEVELOPER
  TESTER = 8, // DEPRECATED
  CENTER_ADMIN = 9, // TODO: Rename to GENERAL_ADMIN
  MEL_REGIONAL_EXPERT = 10, // TODO: Rename to CENTER_ADMIN
}
